/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import static gui.PantallaPrincipal.BreezeSansBold;
import static gui.PantallaPrincipal.BreezeSansRegular;
import java.awt.Font;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author borja
 */
public class DialogoReservas extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public DialogoReservas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.getContentPane().setBackground(java.awt.Color.WHITE);

        habilitarOpciones();

        establecerTipografia();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCliente = new javax.swing.JPanel();
        jLabelDatosCliente = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jPanelReserva = new javax.swing.JPanel();
        jLabelDatosReserva = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelTipoEvento = new javax.swing.JLabel();
        jLabelNumAsistentes = new javax.swing.JLabel();
        jLabelTipoMenu = new javax.swing.JLabel();
        jLabelCongreso = new javax.swing.JLabel();
        jLabelNumDias = new javax.swing.JLabel();
        jLabelAlojamiento = new javax.swing.JLabel();
        jLabelBoda = new javax.swing.JLabel();
        jLabelCapilla = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();
        jComboBoxTipoEvento = new javax.swing.JComboBox<>();
        jSpinnerNumAsistentes = new javax.swing.JSpinner();
        jComboBoxTipoMenu = new javax.swing.JComboBox<>();
        jSpinnerNumDias = new javax.swing.JSpinner();
        jRadioButtonAlojamiento = new javax.swing.JRadioButton();
        jRadioButtonCapilla = new javax.swing.JRadioButton();
        jButtonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva reserva");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(null);

        jPanelCliente.setBackground(new java.awt.Color(255, 255, 255));

        jLabelDatosCliente.setText("Datos del cliente");

        jLabelNombre.setText("Nombre");

        jLabelApellidos.setText("Apellidos");

        jLabelTelefono.setText("Teléfono");

        jLabelDni.setText("DNI");

        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosActionPerformed(evt);
            }
        });

        jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldDni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addComponent(jLabelDatosCliente)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTelefono)
                    .addComponent(jTextFieldDni))
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addComponent(jLabelDatosCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDni)
                    .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanelReserva.setBackground(new java.awt.Color(255, 255, 255));

        jLabelDatosReserva.setText("Datos de la reserva");

        jLabelFecha.setText("Fecha");

        jLabelTipoEvento.setText("Tipo de evento");

        jLabelNumAsistentes.setText("Número de asistentes");

        jLabelTipoMenu.setText("Tipo de menú");

        jLabelCongreso.setText("Congreso");

        jLabelNumDias.setText("Número de días");

        jLabelAlojamiento.setText("¿Necesita alojamiento?");

        jLabelBoda.setText("Boda");

        jLabelCapilla.setText("¿Necesita capilla?");

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha, "dd-MM-yyyy"));
        jSpinnerFecha.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jSpinnerFechaMouseWheelMoved(evt);
            }
        });

        jComboBoxTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso", "Boda" }));
        jComboBoxTipoEvento.setToolTipText("");
        jComboBoxTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoEventoActionPerformed(evt);
            }
        });

        jSpinnerNumAsistentes.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jComboBoxTipoMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bufé", "Wok", "Carta", "Cita con el Chef", "Sin menú" }));

        jSpinnerNumDias.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jRadioButtonAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlojamientoActionPerformed(evt);
            }
        });

        jRadioButtonCapilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCapillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReservaLayout = new javax.swing.GroupLayout(jPanelReserva);
        jPanelReserva.setLayout(jPanelReservaLayout);
        jPanelReservaLayout.setHorizontalGroup(
            jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservaLayout.createSequentialGroup()
                .addComponent(jLabelDatosReserva)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReservaLayout.createSequentialGroup()
                        .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFecha)
                            .addComponent(jLabelTipoEvento)
                            .addComponent(jLabelNumAsistentes)
                            .addComponent(jLabelTipoMenu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSpinnerFecha)
                            .addComponent(jComboBoxTipoEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerNumAsistentes)
                            .addComponent(jComboBoxTipoMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelReservaLayout.createSequentialGroup()
                        .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelReservaLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAlojamiento)
                                    .addComponent(jLabelNumDias)
                                    .addComponent(jLabelCapilla))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReservaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelBoda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)))
                        .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSpinnerNumDias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButtonAlojamiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonCapilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanelReservaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabelCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReservaLayout.setVerticalGroup(
            jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservaLayout.createSequentialGroup()
                .addComponent(jLabelDatosReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoEvento)
                    .addComponent(jComboBoxTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumAsistentes)
                    .addComponent(jSpinnerNumAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoMenu)
                    .addComponent(jComboBoxTipoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelReservaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCongreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNumDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAlojamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBoda)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelCapilla))
                    .addGroup(jPanelReservaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSpinnerNumDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAlojamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonCapilla)))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jButtonConfirmar.setText("Confirmar reserva");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButtonConfirmar)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

    private void jTextFieldDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniActionPerformed

    private void jRadioButtonAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAlojamientoActionPerformed

    private void jRadioButtonCapillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCapillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCapillaActionPerformed

    private void jSpinnerFechaMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jSpinnerFechaMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerFechaMouseWheelMoved

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        JOptionPane.showMessageDialog(this, "Reserva confirmada", "Información", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jComboBoxTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoEventoActionPerformed
        habilitarOpciones();
    }//GEN-LAST:event_jComboBoxTipoEventoActionPerformed

    private void habilitarOpciones() {
        String tipoEvento = (String) jComboBoxTipoEvento.getSelectedItem();

        boolean esCongreso = tipoEvento.equals("Congreso");
        boolean esBoda = tipoEvento.equals("Boda");

        jLabelCongreso.setEnabled(esCongreso);
        jLabelNumDias.setEnabled(esCongreso);
        jLabelAlojamiento.setEnabled(esCongreso);
        jSpinnerNumDias.setEnabled(esCongreso);
        jRadioButtonAlojamiento.setEnabled(esCongreso);

        jLabelBoda.setEnabled(esBoda);
        jLabelCapilla.setEnabled(esBoda);
        jRadioButtonCapilla.setEnabled(esBoda);

    }

    private void establecerTipografia() {
        Font breezeRegular = BreezeSansRegular.deriveFont(12f);
        Font breezeBold = BreezeSansBold.deriveFont(12f);
        Font breezeItalic = BreezeSansRegular.deriveFont(2, 12F);

        JComponent[] textosRegular = {jButtonConfirmar, jComboBoxTipoEvento, jComboBoxTipoMenu, jLabelAlojamiento, jLabelApellidos, jLabelCapilla, jLabelDni, jLabelFecha, jLabelNombre, jLabelNumAsistentes, jLabelNumDias, jLabelTelefono, jLabelTipoEvento, jLabelTipoMenu, jSpinnerFecha, jSpinnerNumAsistentes, jSpinnerNumDias, jTextFieldApellidos, jTextFieldDni, jTextFieldNombre, jTextFieldTelefono
        };
        for (JComponent i : textosRegular) {
            i.setFont(breezeRegular);
        }

        JComponent[] textosNegrita = {jLabelDatosCliente, jLabelDatosReserva};
        for (JComponent j : textosNegrita){
            j.setFont(breezeBold);
        }
        
        JComponent[] textosCursiva = {jLabelBoda, jLabelCongreso};
        for (JComponent k : textosCursiva){
            k.setFont(breezeItalic);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxTipoEvento;
    private javax.swing.JComboBox<String> jComboBoxTipoMenu;
    private javax.swing.JLabel jLabelAlojamiento;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelBoda;
    private javax.swing.JLabel jLabelCapilla;
    private javax.swing.JLabel jLabelCongreso;
    private javax.swing.JLabel jLabelDatosCliente;
    private javax.swing.JLabel jLabelDatosReserva;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumAsistentes;
    private javax.swing.JLabel jLabelNumDias;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoEvento;
    private javax.swing.JLabel jLabelTipoMenu;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelReserva;
    private javax.swing.JRadioButton jRadioButtonAlojamiento;
    private javax.swing.JRadioButton jRadioButtonCapilla;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JSpinner jSpinnerNumAsistentes;
    private javax.swing.JSpinner jSpinnerNumDias;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
