/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.InputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author borja
 */
public class PantallaPrincipal
        extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();

        this.getContentPane().setBackground(java.awt.Color.WHITE);

        this.setIconImage(new ImageIcon(getClass().getResource("/images/salonesTalaveraIco.png")).getImage());

        Icon imagenSalones = new ImageIcon(new ImageIcon(getClass().
                getResource("/images/salonesTalavera.png")).getImage().
                getScaledInstance(jLabelIcono.getWidth(),
                        jLabelIcono.getHeight(),
                        0));

        jLabelIcono.setIcon(imagenSalones);

        jMenuReservas.setFont(BreezeSansRegular.deriveFont(12f));
        jMenuItemNuevaReserva.setFont(BreezeSansRegular.deriveFont(12f));
        jLabelDescripcionBoton.setFont(BreezeSansRegular.deriveFont(12f));
        jButtonAcceder.setFont(BreezeSansRegular.deriveFont(12f));

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAcceder = new javax.swing.JButton();
        jLabelDescripcionBoton = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuReservas = new javax.swing.JMenu();
        jMenuItemNuevaReserva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salones Talavera - Gestión de reservas");
        setBackground(new java.awt.Color(255, 255, 255));

        jButtonAcceder.setText("Acceder");
        jButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederActionPerformed(evt);
            }
        });

        jLabelDescripcionBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescripcionBoton.setText("Accede a la ventana de nueva reserva");

        jLabelIcono.setBackground(new java.awt.Color(255, 255, 255));

        jMenuReservas.setText("Reservas");

        jMenuItemNuevaReserva.setText("Nuevas reserva...");
        jMenuItemNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaReservaActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuItemNuevaReserva);

        jMenuBar1.add(jMenuReservas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDescripcionBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButtonAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDescripcionBoton)
                .addGap(18, 18, 18)
                .addComponent(jButtonAcceder)
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaReservaActionPerformed
        DialogoReservas dialogoReservas = new DialogoReservas(this, true);
        dialogoReservas.setVisible(true);
    }//GEN-LAST:event_jMenuItemNuevaReservaActionPerformed

    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed
        DialogoReservas dialogoReservas = new DialogoReservas(this, true);
        dialogoReservas.setVisible(true);
    }//GEN-LAST:event_jButtonAccederActionPerformed

    public static Font BreezeSansRegular;
    public static Font BreezeSansBold;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.
                    getLogger(PantallaPrincipal.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.
                    getLogger(PantallaPrincipal.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.
                    getLogger(PantallaPrincipal.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.
                    getLogger(PantallaPrincipal.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        try {
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();

            InputStream isRegular = PantallaPrincipal.class.getResourceAsStream("/fonts/BreezeSans-Regular_20150728.ttf");
            BreezeSansRegular = Font.createFont(Font.TRUETYPE_FONT, isRegular);
            ge.registerFont(BreezeSansRegular);

            InputStream isBold = PantallaPrincipal.class.getResourceAsStream("/fonts/BreezeSans-Bold_20150728.ttf");
            BreezeSansBold = Font.createFont(Font.TRUETYPE_FONT, isBold);
            ge.registerFont(BreezeSansBold);
        } catch (Exception e) {
            System.err.println("Error cargando fuentes: " + e.getMessage());
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JLabel jLabelDescripcionBoton;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemNuevaReserva;
    private javax.swing.JMenu jMenuReservas;
    // End of variables declaration//GEN-END:variables
}
